#!/usr/bin/env python
from pathlib import Path
import click
import logging
from lib.rdtp import FileTransferServer, get_transport_factory
from lib.utils import common_options, init_logger


@click.command(
    context_settings={"help_option_names": ["-h", "--help"]},
    help="Upload a file to an rdtp server.",
    no_args_is_help=True,
)
@click.option(
    "-s",
    "--storage",
    type=click.Path(
        exists=True,
        file_okay=False,
        dir_okay=True,
        readable=True,
        path_type=str,
    ),
    help="folder path, used for files upload and download",
)
@common_options(host=True)
@click.pass_context
def main(
    ctx: click.Context,
    storage: Path,
    sack: bool,
    verbose: bool,
    quiet: bool,
    host: str,
    port: int,
):
    init_logger("server.log", verbose, quiet)
    logging.info(f"Starting server at port {port}")
    transport_factory = get_transport_factory(sack)
    addr = ("", port)
    server = FileTransferServer(
        *addr, storage, transport_factory=transport_factory
    )
    server.start()


if __name__ == "__main__":
    main()
